#!/usr/bin/env bash

make mrproper
set -euo pipefail -x
export PATH="$(pwd)/toolchain/clang/bin:${PWD}/toolchain/gcc/bin:${PATH}"
mkdir -p out

export ARCH=arm
export CC=clang
export HOSTCC=clang
export CROSS_COMPILE=arm-linux-androideabi-
export KCFLAGS=-w
export CONFIG_SECTION_MISMATCH_WARN_ONLY=y
export CFLAGS_WARN=-Wunused-but-set-variable

make O=out a02_defconfig
make O=out -j"$(nproc --all)" zImage-dtb 2>&1 | tee build.log
